agents/urls.py
from django.urls import path
from . import views

app_name ='agents'

urlpatterns = [
    path('', views.agentPage.as_view(), name='agentPage'),
    path('create/', views.createAgent.as_view(), name='createAgent'),
]

crm/urls.py
from django.contrib import admin
from django.shortcuts import reverse
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import HomeView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('lead/', include('lead.urls', namespace='lead')),
    path('agents/', include('agents.urls', namespace='agent')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

lead/urls.py
from django.urls import path
from . import views

app_name ='lead'

urlpatterns = [
    path('', views.leadPage.as_view(), name='leadPage'),
    path('create/', views.createLead.as_view(), name='leadcreate'),
    path('<int:pk>/detail/', views.detailLead.as_view(), name='leaddetail'),
    path('<int:pk>/update/', views.updateLead.as_view(), name='leadupdate'),
    path('<int:pk>/delete/', views.deleteLead.as_view(), name='leaddelete'),
]

agents/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import request

class Agent(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)
    age = models.IntegerField()
    email = models.EmailField(max_length=254)

    def __str__(self):
        return self.email

lead/models.py
from django.db import models
from django.contrib.auth.models import User
from agents.models import Agent


class Lead(models.Model):
    agent= models.ForeignKey(Agent, on_delete=models.CASCADE, blank=True, null= True)
    name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return self.name

agents/forms.py
from django import forms
from .models import Agent

class createAgentForm(forms.ModelForm):
    class Meta:
        model = Agent
        fields = [
            'username',
            'age',
            'email',
        ]

lead/forms.py
from django import forms
from django.forms import fields
from .models import Lead

class CreateLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            'name',
            'age',
            'phone_number',
            'agent'
        ]

agents/views.py
from django.shortcuts import render
from django.views import View
from .forms import createAgentForm

from .models import Agent

# agents
class agentPage(View):
    def get(self, request, *args, **kwargs):
        agents = Agent.objects.filter(user = request.user)
        return render(request, 'agents/agent.html',{'agents':agents})

class createAgent(View):
    def get(self, request, *args, **kwargs):
        form = createAgentForm
        return render(request, 'agents/agentcreate.html',{'form':form})
    
    def post(self, request, *args, **kwargs):
        form = createAgentForm(request.POST)
        if form.is_valid():
            agent = form.save(commit=False)
            agent.user = request.user
            agent.save()
        return render(request, 'agents/agentcreate.html',{'form':form})  

crm/views.py
from django.shortcuts import reverse
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model


class HomeView(generic.TemplateView):
    template_name = "home.html"


class SignupView(CreateView):
    template_name ='registration/signup.html' 
    form_class = UserCreationForm

    def get_success_url(self) :
        return reverse('login')

lead/views.py
from django.db.models import query
from django.http import request
from django.shortcuts import render, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from .models import Agent, Lead
from .forms import CreateLeadForm


class leadPage(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        leads = Lead.objects.all()
        return render(request, 'lead/leadpage.html',{'lead':leads})
    # template_name ='lead/leadpage.html'
    # context_object_name = 'lead'

    # def get_queryset(self):
    #     return Lead.objects.filter(user = request.user)


class createLead(LoginRequiredMixin, CreateView):
    template_name = 'lead/createlead.html'
    form_class = CreateLeadForm

    def get_success_url(self) -> str:
        return reverse('lead:leadPage')

class detailLead(LoginRequiredMixin, DetailView):
    template_name = 'lead/detaillead.html'
    context_object_name = 'lead'

    def get_queryset(self):
        return Lead.objects.all()


class updateLead(LoginRequiredMixin, UpdateView):
    template_name = 'lead/updatelead.html'
    form_class = CreateLeadForm

    def get_queryset(self):
        return Lead.objects.all()

    def get_success_url(self) -> str:
        return reverse('lead:leadPage')

class deleteLead(LoginRequiredMixin, DeleteView):
    template_name = 'lead/deletelead.html'

    def get_queryset(self):
        return Lead.objects.all()

    def get_success_url(self) -> str:
        return reverse('lead:leadPage')

agents/templates/agents/agent.html
{% extends 'base.html' %}


{% block content %}
<section class="lead">
    <div class="container-fluid">
    <div class="row justify-content-center align-items-center">
    
        <div class="col-lg-6 py-5">
            <h4 class="list-title text-left">All your Agents are Listed here</h4>
        </div>
        <div class="col-lg-6">
            <h4 class="font-normal text-right font-weight-normal"> <a href="{% url 'agent:createAgent' %}">Create a Agent</a></h4>
        </div>

        {% for item in agents %}
        <div class="col-lg-12 py-2 leaditem">
            <div class="left">
                <i class="lni lni-arrow-right"></i> 
                <span>{{item.username}}</span> 
            </div>
            <div class="right">
                <a href="{% url 'lead:leaddetail' item.pk %}">Detail</a>
                <a href="{% url 'lead:leadupdate' item.pk %}">update</a>
                <a href="{% url 'lead:leaddelete' item.pk %}">Delete</a>
            </div>
    </div>
        {% endfor %}
    
    </div>
</div>
</section>


{% endblock content %}

agents/templates/agents/agentcreate.html
{% extends "base.html" %}

{% block content %}
    <section class="lear_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-title mt-5">
                        <h3 class="contact-title title text-center position-relative">Create a new Agent</h3>
                    </div>
                    <div class="contact-form form-style-four mx-5">
                        <form method='post' class='mx-5'>
                        {% csrf_token %}
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-input mt-3">
                                            <label>{{orm.label}}</label>
                                            <div class="input-items default">
                                                <i class="lni lni-user"></i>
                                                {{form.username}}
                                            </div>
                                    </div> <!-- form input -->
                                </div>

                                <div class="col-md-12">
                                        <div class="form-input mt-3">
                                            <label>{{form.age.label}}</label>
                                            <div class="input-items default">
                                                <i class="lni lni-spiner-solid"></i>
                                                {{form.age}}
                                            </div>
                                    </div> <!-- form input -->
                                </div>

                                <div class="col-md-12">
                                        <div class="form-input mt-3">
                                            <label>{{form.email.label}}</label>
                                            <div class="input-items default">
                                                <i class="lni lni-mail"></i>
                                                {{form.email}}
                                            </div>
                                    </div> <!-- form input -->
                                </div>

                                <div class="col-md-12">
                                    <div class="single-form pt-25 mt-5">
                                        <div class="input-form rounded-buttons">
                                            <button class="main-btn rounded-three" type="submit">Create</button>
                                        </div>
                                    </div> <!-- single form -->
                                </div>  
                                
                                
                            </div> <!-- row -->
                        </form>
                    </div> <!-- contact form -->
                </div>
 
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    
{% endblock content %}

lead/templates/lead/createlead.html
{% extends "base.html" %}



{% block content %}
    <section class="lear_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-title mt-5">
                        <h3 class="contact-title title text-center position-relative">Create a new Lead</h3>
                    </div>
                    <div class="contact-form form-style-four mx-5">
                        <form method='post' class='mx-5'>
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-input mt-3">
                                        <label>Full Name</label>
                                        <div class="input-items default">
                                            <i class="lni lni-user"></i>
                                            {{form.name}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>
                                
                                 <div class="col-md-12">
                                    <div class="form-input mt-3">
                                        <label>Phone Number</label>
                                        <div class="input-items default">
                                            <i class="lni lni-phone"></i>
                                            {{form.phone_number}}
                                            {% comment %} <input type="text" placeholder="01234567890"> {% endcomment %}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                <div class="col-md-12">
                                    <div class="form-input mt-3">
                                        <label>Age</label>
                                        <div class="input-items default">
                                            <i class="lni lni-spiner-solid"></i>
                                            {{form.age}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>
                               

                                <div class="col-md-12">
                                    <div class="form-input mt-3">
                                        <label>Agent</label>
                                        <div class="input-items default">
                                           <i class="lni lni-offer"></i>
                                            {{form.agent}}
                                            {% comment %} <input type="text" placeholder="01234567890"> {% endcomment %}
                                        </div>
                                    </div> <!-- form input -->
                                </div>
                               
                                <div class="col-md-12">
                                    <div class="single-form pt-25 mt-5">
                                        <div class="input-form rounded-buttons">
                                            <button class="main-btn rounded-three" type="submit">Create</button>
                                        </div>
                                    </div> <!-- single form -->
                                </div>
                            </div> <!-- row -->
                        </form>
                    </div> <!-- contact form -->
                </div>
 
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
    
{% endblock content %}

lead/templates/lead/deletelead.html
{% extends "base.html" %}

{% block content %}
    <section class="lear_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-title mt-5">
                        <h3 class="contact-title title text-center position-relative mb-5">Delete Lead</h3>
                    </div>
                        <div class="contact-form form-style-four mx-5 mt-5">
                            <form method = 'post'>
                                {% csrf_token %}
                            <div class="row justify-content-center">
                                 <div class="col-md-7">
                                        <div class="detailBox default">
                                            <i class="lni lni-user"></i>
                                            {{lead.name}}
                                        </div>
                                    </div> <!-- form input -->

                                     <div class="col-md-7">
                                        <div class="form-input mt-3">
                                            <div class="detailBox default">
                                            <i class="lni lni-phone"></i>
                                            {{lead.phone_number}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                 <div class="col-md-7">
                                    <div class="detailBox mt-3">
                                        <div class="input-items default">
                                            <i class="lni lni-spiner-solid"></i>
                                            {{lead.age}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>
                                
                                <div class="col-md-7">
                                    <div class="detailBox mt-3">
                                        <div class="input-items default">
                                           <i class="lni lni-offer"></i>
                                            {{lead.agent}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                <div class="col-md-7">
                                    <div class="single-form pt-25 mt-3 text-center">
                                        <div class="input-form rounded-buttons">
                                            <button class="main-btn rounded-three" type="submit">Delete This Lead</button>
                                        </div>
                                    </div> <!-- single form -->
                                </div>
                                </div>
                            </form>
                                   
                            </div> <!-- row -->
                    </div> <!-- contact form -->
                </div>
 
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
           

{% endblock content %}

lead/templates/lead/detaillead.html
{% extends "base.html" %}

{% block content %}
    <section class="lear_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-title mt-5">
                        <h3 class="contact-title title text-center position-relative mb-5">Lead Detail</h3>
                    </div>
                        <div class="contact-form form-style-four mx-5 mt-5">
                            <div class="row justify-content-center">
                                    <div class="col-md-7">
                                        <div class="detailBox default">
                                            <i class="lni lni-user"></i>
                                            {{lead.name}}
                                        </div>
                                    </div> <!-- form input -->

                                     <div class="col-md-7">
                                        <div class="form-input mt-3">
                                            <div class="detailBox default">
                                            <i class="lni lni-phone"></i>
                                            {{lead.phone_number}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                 <div class="col-md-7">
                                    <div class="detailBox mt-3">
                                        <div class="input-items default">
                                            <i class="lni lni-spiner-solid"></i>
                                            {{lead.age}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                
                                <div class="col-md-7">
                                    <div class="detailBox mt-3">
                                        <div class="input-items default">
                                           <i class="lni lni-offer"></i>
                                            {{lead.agent}}
                                        </div>
                                    </div> <!-- form input -->
                                </div>

                                </div>
                                
                               

                            </div> <!-- row -->
                    </div> <!-- contact form -->
                </div>
 
            </div> <!-- row -->
        </div> <!-- container -->
    </section>
           

{% endblock content %}

lead/templates/lead/leadpage.html
{% extends 'base.html' %} {% block content %}
<section class="lead">
  <div class="container-fluid">
    <div class="row justify-content-center align-items-center">
      <div class="col-lg-6 py-5">
        <h4 class="list-title text-left">All your Lead are Listed here</h4>
      </div>
      <div class="col-lg-6">
        <h4 class="font-normal text-right font-weight-normal">
          <a href="{% url 'lead:leadcreate' %}">Create a Lead</a>
        </h4>
      </div>

      <div class="col-12">
        <div class="assined">
          <h3>Assined</h3>
          {% for item in lead %}
          <div class="col-lg-12 py-2 leaditem">
            <div class="left">
              <i class="lni lni-arrow-right"></i>
              <span>{{item.name}}</span>
            </div>
            <div class="right">
              <a href="{% url 'lead:leaddetail' item.pk %}">Detail</a>
              <a href="{% url 'lead:leadupdate' item.pk %}">update</a>
              <a href="{% url 'lead:leaddelete' item.pk %}">Delete</a>
            </div>
          </div>
          {% endfor %}
        </div>

        <div class="not_assined my-5">
          <h3>Not Assined</h3>
          <div class="col-lg-12 py-2 leaditem">
            <div class="left">
              <i class="lni lni-arrow-right"></i>
              <span>Hello</span>
            </div>
            <div class="right">
              <a href="">Detail</a>
              <a href="">Detail</a>
              <a href="">Detail</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

lead/templates/lead/updatelead.html
{% extends "base.html" %} {% block content %}

<section class="lear_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-7 col-lg-8">
        <div class="section-title mt-5">
          <h3 class="contact-title title text-center position-relative">
            update Lead
          </h3>
        </div>
        <div class="contact-form form-style-four mx-5">
          <form method="post" class="mx-5">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                <div class="form-input mt-3">
                  <label>Full Name</label>
                  <div class="input-items default">
                    <i class="lni lni-user"></i>
                    {{form.name}}
                  </div>
                </div>
                <!-- form input -->
              </div>

              <div class="col-md-12">
                <div class="form-input mt-3">
                  <label>Phone Number</label>
                  <div class="input-items default">
                    <i class="lni lni-phone"></i>
                    {{form.phone_number}}
                  </div>
                </div>
                <!-- form input -->
              </div>

              <div class="col-md-12">
                <div class="form-input mt-3">
                  <label>Age</label>
                  <div class="input-items default">
                    <i class="lni lni-spiner-solid"></i>
                    {{form.age}}
                  </div>
                </div>
                <!-- form input -->
              </div>

              <div class="col-md-12">
                <div class="form-input mt-3">
                  <label>Agent</label>
                  <div class="input-items default">
                    <i class="lni lni-offer"></i>
                    {{form.agent}} 
                  </div>
                </div>
                <!-- form input -->
              </div>

              <div class="col-md-12">
                <div class="single-form pt-25 mt-5">
                  <div class="input-form rounded-buttons">
                    <button class="main-btn rounded-three" type="submit">
                      Update
                    </button>
                  </div>
                </div>
                <!-- single form -->
              </div>
            </div>
            <!-- row -->
          </form>
        </div>
        <!-- contact form -->
      </div>
    </div>
    <!-- row -->
  </div>
  <!-- container -->
</section>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en"> 
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}CRM -  Another Open Source Software {% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'assets/images/favicon-32x32.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/css/LineIcons.2.0.css' %}">    
    <link rel="stylesheet" href="{% static 'css/lead.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/loader.css' %}">
</head>
<body>
    <div class="spin loader">
        <div class="circles">
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="circle"></div>
        </div>
    </div>
  {% include 'header.html' %}

    {% block hero %} {% endblock hero %}
 
    {% block content %} {% endblock content %}

    {% block features %} {% endblock features %}


    {% include 'footer.html' %}
  


    <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

templates/header.html
{% load static %}
<section class="header-area header-one mb-100">
  <div class="navbar-area navbar-one navbar-transparent">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="#">
              <img src="{% static 'assets/images/logo-4.svg' %}" alt="Logo" />
            </a>

            <button
              class="navbar-toggler toogler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarOne"
              aria-controls="navbarOne"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse sub-menu-bar" id="navbarOne">
              <ul class="navbar-nav pl-5">
                <li class="nav-item">
                  <a href="{% url 'home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'lead:leadPage' %}">Lead</a>
                </li>

                <li class="nav-item">
                  <a href="{% url 'agents:agentPage' %}">Agents</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a href="#">About</a>
                </li>
                <li class="nav-item">
                  <a href="#">Resources</a>
                </li>
                <li class="nav-item">
                  <a href="#">CONTACT</a>
                </li>
              </ul>
            </div>

            <div class="navbar-btn d-none d-sm-inline-block">
              <ul>
                {% if request.user.is_authenticated %}
                <li>
                  <a
                    class="light"
                    href="{% url 'logout' %}?next={% url 'login' %}"
                    >Sign Out</a
                  >
                </li>

                {% else %}
                <li>
                  <a class="light mr-3 px-4" href="{% url 'login' %}"
                    >Sign In</a
                  >
                </li>
                <li>
                  <a class="solid px-4" href="{% url 'signup' %}">Sign Up</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </nav>
          <!-- navbar -->
        </div>
      </div>
      <!-- row -->
    </div>
    <!-- container -->
  </div>
  
</section>